name = "dnad"
version = "0.1.0"
license = "license"
author = "Wenbin Yu, Joshua Hodson, Ã˜yvind Rogne"
maintainer = "oyvind.ygre.rogne@sintef.no"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
